### ISSUE TITLE
[OSPP 2023]  Refactor Dubbo Project to Gradle

### ISSUE THREAD

**Issue by chaicho** [apache/dubbo#12696]
## Overview
Since Gradle 3.0, Gradle has been heavily invested in improving the speed of Gradle builds, with features like build cache and compilation avoidance. It is claimed that for the majority of projects, Gradle is 2-10 times faster than Maven. As more and more projects are developed using Gradle and benefit from its features, Dubbo also wants to migrate its project to Gradle.

## Project Deliverables
- Converting the basic structure of Dubbo to Gradle.
- Migrating custom logic based on Maven plugins to Gradle plugins.

### Phase 1 (July 1 - 31): Analysis and Initial Setup

- [ ] Week 1 (July 1 - 7): Analyze the usage of Maven in the project, including project structure, module dependencies, configuration files and plugins.
- [ ] Week 2 (July 8 - 14): Perform initial Gradle configuration for external dependencies.
- [ ]    Week 3 (July 15 - 21): Configure the dependencies between Dubbo modules using Gradle, migrate the Bill of Materials (BOM).
- [ ]     Week 4 (July 22 - 31): Adjust the self-dependencies definition for each module, refine the scope limitations of dependencies and ensure proper configuration of dependencies.

### Phase 2 (August 1 - 7): Detailed Configuration and Plugin Migration

- [ ]     Weeks 4-5 (August 1 - 14): Configure and migrate common plugins.
- [ ]     Weeks 6-7 (August 15 - 31): Configure and migrate custom plugins.
- [ ]   Week 8 (September 1 - 7): Implement configuration for different profiles.

### Phase 3 (September 8 - 30): Completion and Verification

- [ ]  Week 9 (September 8 - 14): Implement verification scripts to validate the migration results.
- [ ]   Weeks 10-11 (September 15 - 30): Make necessary adjustments based on the verification results.

**Comment by AlbumenJ** [comment]
Please translate to English~ :)

**Comment by chaicho** [comment]
> Please translate to English~ :)

Done :)

**Comment by dujie-js** [comment]
May I ask which version of gradle is it based on
