### ISSUE TITLE
[Feature] HTTP/3 Support For Triple Protocol Overview

### ISSUE THREAD

**Issue by oxsean** [apache/dubbo#14296]
## Background

Apache Dubbo is a high-performance RPC framework dedicated to providing excellent service governance capabilities. With the introduction of HTTP/3, its features based on the QUIC protocol offer new possibilities for Dubbo microservices communication. HTTP/3, by reducing latency, increasing transmission speed, enhancing security, improving packet loss resistance, and supporting 0-RTT connections, provides significant performance and reliability improvements for Dubbo in cloud-native environments for microservices communication.

## Technical Solution Summary

This proposal aims to integrate HTTP/3 into Apache Dubbo, supporting all core capabilities defined by the Triple protocol specification on HTTP/3. The construction of capabilities will revolve around the following core parts:

1. **Remoting Protocol Adaptation**: Develop a new remoting module based on netty-incubator-codec-http3, and modify dubbo-rpc-triple to make the existing triple's dependency on remoting compatible with HTTP/3. It also needs to include support for Alt-Svc defined in RFC7838 to implement bootstrapping.
2. **RPC Protocol Adaptation**: The adaptation of the RPC part includes both client and server. For the server, it mainly needs to support the initialization of HTTP/3 UDP Server, INPUT/OUTPUT adaptation, and the modification of TransportListener to support HTTP/3. The client part is mainly about supporting making call requests through HTTP/3, considering HTTP version negotiation, using HTTP/2 for servers that do not support HTTP/3, otherwise upgrading to HTTP/3.
3. **HTTP/3 Core Capabilities Support**: Based on the features of HTTP/3, support backpressure and flow control, support setting and optimizing congestion control algorithms, support frame prioritization.
4. **Performance Testing**: Conduct comprehensive performance testing, including comparison with HTTP/2 implementation and the original Dubbo protocol performance. The test report will cover key indicators such as machine load, response time, throughput under specific concurrency, latency, packet loss rate, and packet damage rate.

![image](https://github.com/apache/dubbo/assets/716461/9407a61b-009f-4f41-bcc8-97c128597513)

## Supported capabilities
1. Server part: Implemented server port sharing, adapted http3 frame to triple model, adapted control signaling, reused the existing HttpWriteQueue to improve performance
2. Client part: Refactored NettyConnectionClient and ClientStream to support HTTP/2 and HTTP/3, reusing existing code as much as possible, including reconnection, QueuedCommand, and http3 frame adaptation
3. RPC call methods: Covered the three triple call methods: UNARY, SERVER_STREAM, BI_STREAM
4. Call protocol fully supports HTTP, REST, and gRPC
6. Configurable to enable HTTP3 globally or enable for specific providers or consumers
7. Server-side protocol negotiation based on Alt-Svc

## Performance 
![image](https://github.com/apache/dubbo/assets/716461/cd36e115-582d-4f04-ad19-9037583a1835)
![image](https://github.com/apache/dubbo/assets/716461/be817f1b-8fec-4744-8a3f-189e52893002)

## Tasks
The following are the tasks that need to be completed for release

- [x] SSL certificate configuration support
- [ ] Flow control support
- [x] Protocol parameter configuration
- [x] HTTP version negotiation on the consumer side
- [ ] Benchmark
- [ ] Native support validation #14297
- [ ] Unit testing & integration testing
- [x] User manual
- [x] Examples

## Planning
We want to support HTTP/3 in the 3.3 release. If you are interested in the HTTP/3 protocol and would like to collaborate, please contact me on DingTalk: oxsean

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
