### ISSUE TITLE
[Feature] Improved meta support for consul in dubco-spi-extensions 3.3.x

### ISSUE THREAD

**Issue by eduosi** [apache/dubbo#14870]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Descriptions

In version 3.3.0, dubco-metadata-report-consul cannot map services and apps at all, cannot subscribe to services, and the corresponding implementation code is not found in the 3.3.1 branch.

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by heliang666s** [comment]
Hello thanks for the feedback, the implementation of consul is in [dubbo-spi-extension](https://github.com/apache/dubbo-spi-extensions/tree/master/dubbo-metadata-report-extensions/dubbo-metadata-report-consul), and the specific usage method can be found in [dubbo-spi-samples](https://github.com/apache/dubbo-spi-samples/tree/main/5-dubbo-spi-metadata-samples/samples-spi-metadata/samples-spi-metadata-consul). There is already an [issue](https://github.com/apache/dubbo/issues/14868) that reflects the same problem, and a PR has been filed. If you still can't use it after referring to it, please give us a detailed error log.@eduosi

**Comment by eduosi** [comment]
> Hello thanks for the feedback, the implementation of consul is in [dubbo-spi-extension](https://github.com/apache/dubbo-spi-extensions/tree/master/dubbo-metadata-report-extensions/dubbo-metadata-report-consul), and the specific usage method can be found in [dubbo-spi-samples](https://github.com/apache/dubbo-spi-samples/tree/main/5-dubbo-spi-metadata-samples/samples-spi-metadata/samples-spi-metadata-consul). There is already an [issue](https://github.com/apache/dubbo/issues/14868) that reflects the same problem, and a PR has been filed. If you still can't use it after referring to it, please give us a detailed error log.@eduosi

<img width="1572" alt="图片" src="https://github.com/user-attachments/assets/365c7750-16b6-49bd-97c6-05daa711de32">
<img width="1659" alt="图片" src="https://github.com/user-attachments/assets/f9c2cfc8-aa40-4c0a-9997-fa58fdbad903">
Because there's no rewriting methods on the interface MetadataReport registerServiceAppMapping ConsulMetadataReport, not registered service and application of mapping relation with the consul; The method getServiceAppMapping in the MetadataReport interface is also overridden so that the mapping between the fetching service and the application is always empty.

[dubbo-test.zip](https://github.com/user-attachments/files/17666553/dubbo-test.zip)

This is a simple demo that uses consul for both the registry and the metadata center

1. Change the registry address and metadata center address in aplication.yml to the addresses of consul.
2. `cd dubbo-test-parent && mvn clean install`
3. run dubbo-test-provider
4. run dubbo-test-consumer
5. go to 'http://127.0.0.1:8081/test/echo'

**Comment by eduosi** [comment]
> Hello thanks for the feedback, the implementation of consul is in [dubbo-spi-extension](https://github.com/apache/dubbo-spi-extensions/tree/master/dubbo-metadata-report-extensions/dubbo-metadata-report-consul), and the specific usage method can be found in [dubbo-spi-samples](https://github.com/apache/dubbo-spi-samples/tree/main/5-dubbo-spi-metadata-samples/samples-spi-metadata/samples-spi-metadata-consul). There is already an [issue](https://github.com/apache/dubbo/issues/14868) that reflects the same problem, and a PR has been filed. If you still can't use it after referring to it, please give us a detailed error log.@eduosi

Metadata support for consul [apache/dubbo-spi-extensions#560](https://github.com/apache/dubbo-spi-extensions/pull/560)
